project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Paulina"
  search: false
  twitter-card:
    creator: "@pawleenam"
  navbar:
    #left:
      #- text: "Hello" 
      #  href: about.qmd
      #- text: "Writing"
      #  href: writing/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/pawleenam
      - icon: linkedin
        href: https://www.linkedin.com/in/paulina-moskwa/
      - icon: github
        href: https://github.com/paulinamoskwa

metadata-files: [nbdev.yml]

